# Question 11: Visualize the feature map generated by convolution using PyTorch.

import torch
import matplotlib.pyplot as plt

image = torch.tensor([[1, 2, 3, 0, 1],
                      [4, 5, 6, 1, 2],
                      [7, 8, 9, 2, 3],
                      [1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 0]], dtype=torch.float32)

image = image.unsqueeze(0).unsqueeze(0)

kernel = torch.tensor([[ 1,  0, -1],
                       [ 1,  0, -1],
                       [ 1,  0, -1]], dtype=torch.float32)

kernel = kernel.unsqueeze(0).unsqueeze(0)

feature_map = torch.nn.functional.conv2d(image, kernel)
feature_map = feature_map.squeeze()

print("Feature Map:\n", feature_map)

feature_map = feature_map.detach().numpy()

plt.imshow(feature_map, cmap='gray')
plt.title("Feature Map")
plt.colorbar()
plt.show()
